### ISSUE TITLE
Is it interactive?

### ISSUE THREAD

**Issue by olpeh** [jefersondaniel/cyclejs-notes#1]
Hi. Your project looks really nice.

However, I'm unable to test it. Clicking add new note seems to do nothing.

"Should it" be working at the moment?

**Comment by jefersondaniel** [comment]
Yes, but there is a problem with adding notes before a initial response from the API. The heroku dyno jsonapi-notes.herokuapp.com is temporary unavailable

**Comment by olpeh** [comment]
Ok. Good to know.
